name: npm test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
        redis:
          image: redis
          ports:
            - 6379
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install
        - run: npm run build --if-present
        - run: npm test
